### ISSUE TITLE
MyWebSite

### ISSUE THREAD

**Issue by FabioZTessitore** [ClaudioTazza/Dojo#10]
in attesa

**Comment by ClaudioTazza** [comment]
Mi dia qualche indicazione

**Comment by FabioZTessitore** [comment]
ci sono varie cose che non vanno bene.

 - Il file css non deve contenere il link al font, deve stare nell'html
 - sempre nel file css, l'ultima riga serve a selezionare il font, ma a quale selettore appartiene?
 - ad essere pignoli dovevi usare le pagine html dell'altro esercizio. Non è una cosa importante, ma almeno due pagine dovresti usarle per capire come gestire il css e i font

**Comment by FabioZTessitore** [comment]
il file html deve contenere il link ai font
