### ISSUE TITLE
conversioni2

### ISSUE THREAD

**Issue by FabioZTessitore** [ClaudioTazza/Dojo#12]
Carina la soluzione che hai trovato.

Solo un paio di osservazioni:

```c
while(n < 255){
    n *= base;
  }
  
  for(int bitVal = n/base; ...
```

Non si riesce a trovare un altro modo per evitare la divisione nell'inizializzazione del for?

```c
printf("%c", digit + 55);
```

Quel 55 non si può vedere ... metti il carattere

**Comment by FabioZTessitore** [comment]
la divisione l'hai solo spostata ... cmq va bene

il '7' ancora non va bene perche' non rende l'idea di cosa stai facendo
forse un digit - 10 + 'A' puo' aiutare

**Comment by ClaudioTazza** [comment]
Ha un consiglio per evitare la divisione?

**Comment by FabioZTessitore** [comment]
no

**Comment by FabioZTessitore** [comment]
per determinare il numero di cifre si usa il logaritmo (approssimato all'intero successivo)
`math.log(255, base)`

**Comment by ClaudioTazza** [comment]
Capito
